workflows:
  ios-workflow:
    name: GreenWave iOS Build
    instance_type: mac_mini_m2
    environment:
      groups:
        - mapbox
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Configuration du token Mapbox (iOS)
        script: |
          echo "machine api.mapbox.com login mapbox password $MAPBOX_DOWNLOADS_TOKEN" > ~/.netrc
          chmod 0600 ~/.netrc
      - name: Get Flutter packages
        script: flutter pub get
      - name: Generate Podfile and Fix iOS Version
        script: |
          # 1. Demande au Mac de Codemagic de générer le Podfile manquant
          flutter build ios --config-only
          # 2. Force la version 14.0 dans le fichier généré
          sed -i '' "s/^# platform :ios.*/platform :ios, '14.0'/g" ios/Podfile
      - name: Install iOS Pods
        script: |
          cd ios
          pod install
      - name: Build iOS app & Create IPA for AltStore
        script: |
          # 1. Compilation
          flutter build ios --release --no-codesign
          
          # 2. Retour à la racine pour éviter de se perdre
          cd $CM_BUILD_DIR
          rm -rf Payload GreenWave.ipa
          mkdir Payload
          
          # 3. Copie forcée du VRAI dossier compilé (le -L force la copie des fichiers lourds, pas des raccourcis)
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            cp -RL build/ios/iphoneos/Runner.app Payload/
          elif [ -d "build/ios/Release-iphoneos/Runner.app" ]; then
            cp -RL build/ios/Release-iphoneos/Runner.app Payload/
          else
            echo "Erreur: Le vrai Runner.app est introuvable."
            exit 1
          fi
          
          # 4. Zippage propre pour AltStore (on exclut les fichiers cachés Mac qui font planter l'install)
          zip -qry GreenWave.ipa Payload -x "*.DS_Store" -x "__MACOSX/*"
          
    artifacts:
      - GreenWave.ipa